# Generated by Django 3.2.9 on 2021-11-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='county', max_length=254),
            preserve_default=False,
        ),
    ]
