# Generated by Django 3.2.9 on 2021-11-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_frame_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
