# Generated by Django 3.2.9 on 2021-12-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='review_text',
            new_name='review_message',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='user',
            new_name='user_name',
        ),
    ]
